# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AuthSns' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!
    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'
    pod 'SDWebImage'

  # Pods for AuthSns

  target 'AuthSnsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
